baseurl: "/Web-Teaching/"
remote_theme: chauff/cse-theme

collections:
  lectures:
    output: true
    sort_by: ordering
  practicals:
    output: true
    sort_by: ordering
  extras:
    output: true

line1Title: CSE1500   
line2Title: Web Technology 
line3Title: Node.js, JavaScript, CSS, HTTP, HTML
tabTitle: CSE1500 TU Delft course materials.
warning: The materials are currently being updated for the 2021/22 course edition. Some content may still change.
exam: false

footerImage: ../images/tudelft-ewi-light-footer.svg
headerImage: ../images/tudelft_ewi_bw.jpg
cssTheme: themes/light-grey.css
cssCodeTheme: themes/code/dracula.css

plugins:
  - jemoji
  - jekyll-remote-theme
  
markdown: kramdown
# !github-pages! mandatory › https://help.github.com/articles/using-jekyll-with-pages/#configuration-settings-you-cannot-change
# Since Jekyll 3 the default highlighter is Rouge (replaced Pygments.rb in v44)
highlighter: rouge

# More › http://kramdown.gettalong.org/quickref.html
# Options › http://kramdown.gettalong.org/options.html
kramdown:
  input:          GFM
  # https://github.com/jekyll/jekyll/pull/4090
  syntax_highlighter: rouge

  # Rouge Highlighter in Kramdown › http://kramdown.gettalong.org/syntax_highlighter/rouge.html
  # span, block element options fall back to global
  syntax_highlighter_opts:
    # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: 'highlight'
    #line_numbers: true # bad idea, spans don't need linenos and would inherit this option
    span:
      line_numbers: false
    block:
      line_numbers: false
